# Use an official Python runtime as a parent image
FROM continuumio/anaconda3:2018.12

RUN apt-get update
RUN apt-get install -y build-essential 

# Install any needed packages specified in requirements.txt
RUN conda install -c conda-forge python-igraph 

# libiconv seems to be necessary for conda's python-igraph to work correctly
RUN conda install libiconv

RUN pip install tulip-python ndex-dev

RUN pip install simplejson mygene

RUN echo a

RUN git clone -b 'song_cytoCD' --depth 1 https://github.com/Song-Cao/ddot.git ddot

RUN cd ddot && make
RUN cd ..

RUN pip install ddot/
RUN mv ddot/examples /ddot_examples

RUN pip install louvain
RUN pip install flask_restful

WORKDIR /ddot_examples
